before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/edge-agent/
    binary: edge-agent
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - id: edge-agent-amd64
    image_templates:
      - "warrantdev/edge-agent:{{ .Tag }}-amd64"
      - "warrantdev/edge-agent:latest-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    skip_push: false
    dockerfile: "Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: edge-agent-arm64
    image_templates:
      - "warrantdev/edge-agent:{{ .Tag }}-arm64"
      - "warrantdev/edge-agent:latest-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    skip_push: false
    dockerfile: "Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "warrantdev/edge-agent:{{ .Tag }}"
    image_templates:
      - "warrantdev/edge-agent:{{ .Tag }}-amd64"
      - "warrantdev/edge-agent:{{ .Tag }}-arm64"
  - name_template: "warrantdev/edge-agent:latest"
    image_templates:
      - "warrantdev/edge-agent:latest-amd64"
      - "warrantdev/edge-agent:latest-arm64"
