name: Build Warrant Edge Agent

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Env
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Build Agent
        run: make build
        working-directory: cmd/edge-agent
      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: check
